###############################################################
#  Generated by:      Cadence Innovus 16.13-s045_1
#  OS:                Linux x86_64(Host ID toke.fransg.eit.lth.se)
#  Generated on:      Wed Feb 21 14:25:02 2024
#  Design:            jollof_top
#  Command:           create_ccopt_clock_tree_spec -file ./ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Clocks present at pin clk
#   clk (period 10.000ns) in timing_config Clock_Constraint([/h/dc/o/si3116uw-s/icp1matrix/PnR/jollof_top.dat/libs/mmmc/jollof_top.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group

set_ccopt_property target_max_trans_sdc -delay_corner SS -late -clock_tree clk 0.200
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner SS -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner SS -late -fall -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -rise -clock_tree clk 0.500
set_ccopt_property source_latency -delay_corner FF -late -fall -clock_tree clk 0.500
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 10

# Skew group to balance non generated clock:clk in timing_config:Clock_Constraint (sdc /h/dc/o/si3116uw-s/icp1matrix/PnR/jollof_top.dat/libs/mmmc/jollof_top.sdc)
create_ccopt_skew_group -name clk/Clock_Constraint -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/Clock_Constraint true
set_ccopt_property extracted_from_clock_name -skew_group clk/Clock_Constraint clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/Clock_Constraint Clock_Constraint
set_ccopt_property extracted_from_delay_corners -skew_group clk/Clock_Constraint {SS FF}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

